### ISSUE TITLE
Does not work with release candidates

### ISSUE THREAD

**Issue by tvdeyen** [hmans/bumpy#1]
I wanted to bump my gem version from `2.2.rc11` to `2.2.rc12`

Sadly it bumped to `2.2.1`

**Comment by tvdeyen** [comment]
`"rc11".next => "rc12"` ;)

**Comment by hmans** [comment]
Just fixed it, but using .next of course is even more awesome. Coming right up!

**Comment by tvdeyen** [comment]
Damn, I just forked :P

**Comment by hmans** [comment]
`gem update bumpy`
